### ISSUE TITLE
Upgrade Redigo version

### ISSUE THREAD

**Issue by yfei1** [Bose/minisentinel#3]
Current go.mod file automatically pulled the redigo dependency v2.0.0, which is not the latest release - yes, their latest release is v1.7.1 but not v2.0.0. This would result in dependency incompatibilities for users who are using the v1.7 version since there are features only available in the 1.7 version. It would be great if minisentinel could support the edge features e.g. redisPool.DialContext.

**Comment by Jim-Lambert-Bose** [comment]
redigo is a semvar mess at the moment: https://github.com/gomodule/redigo/issues/366
and has been a mess since it made that v2 release on Mar 15, 2018.  

Hum... I'll see what I can do today to make things better for minisentinel

**Comment by Jim-Lambert-Bose** [comment]
fix has been merged.
